### ISSUE TITLE
Training set

### ISSUE THREAD

**Issue by bcba25** [Emadeldeen-24/face-anti-spoofing#1]
Hi @Emadeldeen-24 , first of all, thank you for sharing this code. I'm relatively new in ML. Could you provide a training process for this NN? Or at least explain on how to use  model for training on own dataset. Thanks!

**Comment by bcba25** [comment]
Could you please explain on how to combine these:
`These frames are in RGB and they are passed to a ResNet18 model. Also rPPG features are extracted from these frames and passed to a Dense layer. These two models are then merged together.`

**Comment by emadeldeen24** [comment]
I merged them using `concatenate` https://keras.io/layers/merge/

**Comment by bcba25** [comment]
@Emadeldeen-24 could you provide a training script for studying please? 
It means you have two models, one for images and one for rPPG features ?

**Comment by emadeldeen24** [comment]
- Work is still in progress, can't share it now. But will do soon.
- Yes, I guess this clear in the description.

**Comment by bcba25** [comment]
@Emadeldeen-24 alright, thanks.

**Comment by hxdef2517** [comment]
@Emadeldeen-24 sorry for offtop, is there a way to contact you to discuss something ?
